OrdererOrgs:
  - Name: Orderer
    Domain: nebula.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.nebula.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1
